[project]
name = "assistant-surete-nucleaire"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mahyr", email = "106538282+MahyrF@users.noreply.github.com" }
]
requires-python = ">=3.10"
dependencies = []

[project.scripts]
assistant-surete-nucleaire = "assistant_surete_nucleaire:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
